Connect React Redux with external API
emhamza/book-strore-App pull request #4
Opened 2023-05-10 17:29 UTC by emhamza

**This is the most interesting milestone of the bookstore app so far.  I am happy that I have managed to complete the following tasks:**

- [ ] Connect the Redux app with the bookstore API
- [ ] Add functionality of get, post and delete book to my bookstore app

2023-05-10 17:40 UTC, DammyShittu requested changes
Hi @emhamza,

## Highlights
✔️ API feature

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 17:40 UTC, DammyShittu commented on src/components/BookForm.js
>        setAuthor('');
- [ ] After adding a book it does not appear on the page immediately. I have to reload the browser for the newly added book to show up. Kindly note that when a book is added it should be displayed without having to reload the page. Kindly fix that.

2023-05-10 18:02 UTC, emhamza commented on src/components/BookForm.js
>        setAuthor('');
Sure thing, thank  you so much for pointing that out! @DammyShittu

2023-05-11 09:16 UTC, Davidosky007 approved these changes
Hi @emhamza 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* API works fine 👍 
* Good looking readme 👍 
* Proper use of Gitflow 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 09:19 UTC, merged